dirt:
  additive: false
  decay_factor: 1.0
  event_probability: 0.03
  kernel_factor: 160
  kernel_size: 151
  old_noise: null
  sigma: 29
fog:
  airlight: 245
  minimum_distance: 12
  per_channel_airlight: false
smoke:
  airlight: 128
  minimum_distance: 12
  per_channel_airlight: false
gaussian_blur:
  kernel_size: 27
  stdev: 0.0
gaussian_noise:
  mean: 0.0
  stdev: 80.0
gaussian_noise_conv:
  kernel_size: 19
  mean: 0.0
  stdev: 140.0
rain:
  additive: true
  decay_factor: 0.98
  event_probability: 0.3
  kernel_factor: 150
  kernel_size: 201
  old_noise: null
  sigma: 39
salt_and_pepper:
  pepper_prob: 0.03
  salt_prob: 0.03
salt_and_pepper_conv:
  kernel_size: 9
  pepper_prob: 0.0003
  salt_prob: 0.0003
  sigma: 1.23
